project_name: secretium
report_sizes: true

env_files:
  github_token: ~/.github_token

before:
  hooks:
    - go mod download
    - go mod tidy
    - go run github.com/google/wire/cmd/wire@latest ./...
    - go run github.com/a-h/templ/cmd/templ@latest generate ./...

builds:
  - id: default
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64]

upx:
  - ids: [default]
    enabled: true
    compress: best
    lzma: true
    brute: true
    goos: [linux]
    goarch: [amd64, arm64]

release:
  ids: [default]
  draft: true
  replace_existing_draft: true
  target_commitish: "{{ .Commit }}"
  prerelease: auto
  mode: replace
  header: |
    ## ✨ The {{ .ProjectName }} `{{ .Tag }}` release

    <img width="100%" alt="secretium banner" src="https://raw.githubusercontent.com/secretium/.github/main/images/secretium-project-banner.svg">
  footer: |
    ## How to update?

    For [Docker][docker_url] users (GNU/Linux only):

    ```console
    docker pull secretium/secretium:latest
    ```

    For other ways (any platforms): manually download and re-install a ready-made package from the `Assets` section.

    > 💡 Note: See the [Complete user guide][docs_url] to get a general information.

    ## Your help to improve Secretium

    We would be truly grateful for any help with:

    - Creating tests and benchmarks for code;
    - Improving existing functions, structs, or tests;
    - Feature requests with interesting functions that would be good to add;
    - Say a few words about the project on your social networks and blogs (Dev.to, Medium, Хабр, and so on).

    Your PRs & issues are welcome! Thanks 😉

    <!-- Links -->

    [brew_url]: https://brew.sh
    [docker_url]: https://www.docker.com
    [docs_url]: https://secretium.org
  disable: false
  skip_upload: false

dockers:
  - id: "{{ .ProjectName }}_amd64"
    ids: [default]
    use: buildx
    skip_push: auto
    image_templates:
      - "secretium/{{ .ProjectName }}:latest-amd64"
      - "secretium/{{ .ProjectName }}:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--platform=linux/amd64"
    push_flags:
      - "--tls-verify=false"
  - id: "{{ .ProjectName }}_arm64"
    ids: [default]
    use: buildx
    skip_push: auto
    image_templates:
      - "secretium/{{ .ProjectName }}:latest-arm64"
      - "secretium/{{ .ProjectName }}:{{ .Tag }}-arm64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--platform=linux/arm64"
    push_flags:
      - "--tls-verify=false"

docker_manifests:
  - name_template: "secretium/{{ .ProjectName }}:latest"
    skip_push: auto
    image_templates:
      - "secretium/{{ .ProjectName }}:latest-amd64"
      - "secretium/{{ .ProjectName }}:latest-arm64"
  - name_template: "secretium/{{ .ProjectName }}:{{ .Tag }}"
    skip_push: auto
    image_templates:
      - "secretium/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "secretium/{{ .ProjectName }}:{{ .Tag }}-arm64"

nfpms:
  - maintainer: Vic Shóstak <koddr.me@gmail.com>
    description: |
      A smart self-hosted tool for sharing secrets to your friends, colleagues, or anyone!
    homepage: "https://github.com/secretium/{{ .ProjectName }}"
    license: Apache 2.0
    formats: [deb, rpm]

archives:
  - format_overrides:
      - goos: windows
        format: zip
    files: [LICENSE, README.md]

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc
  abbrev: -1
  filters:
    exclude: ["^*.md", "^*.ya?ml"]
  groups:
    - title: New features
      regexp: ^.*?((A|a)dd)|(N|n)ew)|((F|f)eature).*?$
      order: 0
    - title: Bug fixes
      regexp: ^.*?((B|b)ug)|((F|f)ix).*?$
      order: 1
    - title: Improvements
      regexp: ^.*?(I|i)mprove.*?$
      order: 2
    - title: Updates
      regexp: ^.*?(U|u)pdate.*?$
      order: 3
    - title: Security issues
      regexp: ^.*?(S|s)ecurity.*?$
      order: 4
    - title: Delete unused or stale
      regexp: ^.*?((D|d)elete)|((U|u)nused)|((S|s)tale).*?$
      order: 5
    - title: Others
      order: 999
